/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import Modelo.bean.CadastroCliente;
import Modelo.bean.NumeroPedido;
import Modelo.bean.Pedido;
import Modelo.bean.Produto;
import Modelo.dao.CadastroClienteDao;
import Modelo.dao.Pedidodao;
import Modelo.dao.Produtodao;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.text.DateFormatter;

/**
 *
 * @author Matheus
 */
public class TelaPedidos extends javax.swing.JFrame {

    /**
     * Creates new form TelaPedidos
     */
    public TelaPedidos() {
        initComponents();

        listadeproduto();
        listacliente();
        tamanholistapedido();
        somapedido();
        somartotal();
      
//      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listadeproduto = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        listadecliente = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        listapedido = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        totalpedido = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        listadeproduto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo Produto", "Nome Produto", "Valor Produto"
            }
        ));
        listadeproduto.setGridColor(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(listadeproduto);

        listadecliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome do Cliente"
            }
        ));
        jScrollPane2.setViewportView(listadecliente);

        listapedido.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cod Pedido", "Cod Produto", "Qtd", "Nome Produto", "Vlr Prod", "Vlr Ped", "Nome Cliente"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        listapedido.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        listapedido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listapedidoMouseClicked(evt);
            }
        });
        listapedido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                listapedidoKeyPressed(evt);
            }
        });
        jScrollPane3.setViewportView(listapedido);

        jButton1.setText("Inserir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Excluir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Confirmar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Cancelar");

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/WhatsApp Image 2021-08-25 at 12.38.07.jpeg"))); // NOI18N
        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(262, 262, 262)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(218, 218, 218)
                        .addComponent(jButton3)
                        .addGap(42, 42, 42)
                        .addComponent(jButton4)
                        .addGap(66, 66, 66)
                        .addComponent(totalpedido, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 329, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jButton3)
                    .addComponent(totalpedido, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(106, 106, 106))
        );

        jMenu3.setText("Inicio");

        jMenuItem5.setText("Tela Inicial");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem5);

        jMenuBar1.add(jMenu3);

        jMenu1.setText("Telas");

        jMenuItem1.setText("Atualização de Produto");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Tela Informação de Produto");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Cadastro");

        jMenuItem3.setText("Cadastro de Produto");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuItem4.setText("Cadastro de Cliente");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 652, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // Botão inserir
        
        DefaultTableModel modelo = (DefaultTableModel) listapedido.getModel();
        
        
        if (listadeproduto.getSelectedRow() != -1 ) {
          
                if(listadecliente.getSelectedRow() != -1){
                       
             int qtd = 1;
            int codprod = (int) listadeproduto.getValueAt(listadeproduto.getSelectedRow(), 0);
            String nomeprod = listadeproduto.getValueAt(listadeproduto.getSelectedRow(), 1).toString();
            float valorprod = Float.parseFloat(listadeproduto.getValueAt(listadeproduto.getSelectedRow(), 2).toString());
            String nomecliente = (listadecliente.getValueAt(listadecliente.getSelectedRow(),0).toString());
           float vlrtotal = 0;
            Buscanumerodepedido  npedido = new Buscanumerodepedido();
            int nped = npedido.buscarnumero();
            
            
                  
          Object [] pedido = {nped,codprod,qtd,nomeprod,valorprod,vlrtotal,nomecliente};  
            modelo.addRow(pedido);
            
                }else {
                   JOptionPane.showMessageDialog(null, "Selecione um Cliente. ");
                    
                }
        } else {
            
            JOptionPane.showMessageDialog(null, "Selecione um Produto  ");
        }
        
        somapedido();
        somartotal();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        DefaultTableModel modelo = (DefaultTableModel) listapedido.getModel();
        
        
        if(listapedido.getSelectedRow() != -1){
            diminuirvalortotal();
            modelo.removeRow(listapedido.getSelectedRow());
            
            
           
        }else {
            
            JOptionPane.showMessageDialog(null, "Selecione o item que deseja excluir ");
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        Buscanumerodepedido numped = new Buscanumerodepedido();
        
        Pedidodao pdao = new Pedidodao();
        
        
        for(int i = 0 ; i < listapedido.getRowCount(); i++){
           Data date = new Data();
           String data = date.buscardata();
           String mes = date.buscarmes();
           String ano = date.buscarano();
            Pedido pedido = new Pedido();
            
            List <Pedido> ped = new ArrayList <>();
            
            pedido.setNumeropedido((int) listapedido.getValueAt(i, 0));
            pedido.setNumeroproduto(Integer.parseInt(listapedido.getValueAt(i,1).toString()));
            pedido.setQtd(Integer.parseInt(listapedido.getValueAt(i, 2).toString()));
            pedido.setNomeproduto(listapedido.getValueAt(i, 3).toString());
            pedido.setVlrunidade(Float.parseFloat(listapedido.getValueAt(i, 5).toString()));
            pedido.setNomecliente(listapedido.getValueAt(i, 6).toString());
            pedido.setData(data);
            pedido.setMespedido(mes);
            pedido.setAnopedido(ano);
            pedido.setValorpedido(Float.parseFloat(totalpedido.getText()));
            

            ped.add(pedido);
            
            pdao.inserirpedido(ped);
            
           
            
            
            
            
            
        }
        
        numped.atulizarnumeropedido();
        zerarjtablepedido();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void listapedidoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_listapedidoKeyPressed

        int keycod = evt.getKeyCode();
        
        if (keycod == KeyEvent.VK_ENTER){
            
            somapedido();
            somartotal();
        }


    }//GEN-LAST:event_listapedidoKeyPressed

    private void listapedidoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listapedidoMouseClicked
        // TODO add your handling code here:
        if(evt.getClickCount() == 1){
        somapedido();
        somartotal();
        }
    }//GEN-LAST:event_listapedidoMouseClicked

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        
        
        TelaPrincipal tela = new TelaPrincipal();
        tela.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        
        TelaAtualizacaodeProduto tela = new TelaAtualizacaodeProduto();
        tela.setVisible(true);
        this.dispose();
        
        
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        
        TelaInformacoesProduto tela = new TelaInformacoesProduto();
        
        tela.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        
        CadastroProduto tela = new CadastroProduto();
        tela.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        
        TelaCadastroClientes tela = new TelaCadastroClientes ();
        
        tela.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPedidos().setVisible(true);
            }
        });
    }

    public void listadeproduto() {

        DefaultTableModel modelo = (DefaultTableModel) listadeproduto.getModel();
        modelo.setNumRows(0);
        listadeproduto.setBackground(Color.WHITE);
        listadeproduto.getParent().setBackground(Color.WHITE);
       
        Produtodao pdao = new Produtodao();

        for (Produto p : pdao.Listarproduto()) {

            modelo.addRow(new Object[]{
                p.getCodproduto(),
                p.getNomeproduto(),
                p.getPrecoproduto()

            });
        }
    }

    public void listacliente() {
        
        DefaultTableModel modelo = (DefaultTableModel) listadecliente.getModel();
        
        modelo.setNumRows(0);

        CadastroClienteDao cadcliente = new CadastroClienteDao();

        for (CadastroCliente cad : cadcliente.ListarCliente()) {

            modelo.addRow(new Object[]{
                cad.getNome()

            });

        }
    }
    
    
    
    
    public void tamanholistapedido(){
        listapedido.setAutoResizeMode(listapedido.AUTO_RESIZE_OFF);
        listapedido.getColumnModel().getColumn(0).setMaxWidth(80);
        listapedido.getColumnModel().getColumn(1).setMaxWidth(80);
        listapedido.getColumnModel().getColumn(2).setMaxWidth(60);
        listapedido.getColumnModel().getColumn(3).setPreferredWidth(190);
        listapedido.getColumnModel().getColumn(4).setPreferredWidth(80);
        listapedido.getColumnModel().getColumn(5).setPreferredWidth(80);
        listapedido.getColumnModel().getColumn(6).setPreferredWidth(222);
       
        
    }
    
    
    public void somapedido(){
          for(int i = 0 ; i < listapedido.getRowCount() ; i++){
            
            float valor = Float.parseFloat(listapedido.getValueAt(i,4).toString());
            int qtd = Integer.parseInt(listapedido.getValueAt(i, 2).toString());
            float total = valor*qtd;
            
//            System.out.println("valor da coluna  : " + valor);
//            System.out.println("valor de coluna qtd :" + qtd);
//            
//            System.out.println("valor total : " + total);
            
            listapedido.setValueAt(total, i, 5);
          
            
            
        }
        
    }

    public void somartotal(){
        
      float total = 0;
            for(int i = 0 ; i < listapedido.getRowCount() ; i++){
            
            
            float valor =Float.parseFloat( listapedido.getValueAt(i, 5).toString());
            
            total = total + valor;  
            
       totalpedido.setText("" + total);
            
        }
        
    }
    
    public void diminuirvalortotal(){
        
            
         
        float valortotalpedido= Float.parseFloat(totalpedido.getText());
        float valortotal = 0;
        float valordalista  =Float.parseFloat(listapedido.getValueAt(listapedido.getSelectedRow(), 5).toString());
      
        
        valortotal = valortotalpedido - valordalista;

        
        totalpedido.setText("" + valortotal);
  
    }
    
    public void zerarjtablepedido (){
        
       DefaultTableModel modelo = (DefaultTableModel) listapedido.getModel();
       modelo.setRowCount(0);
       
       String zerar ;
        totalpedido.setText("");
          
       
      for (int i = 0 ; i < listapedido.getRowCount(); i++){
          
          modelo.setValueAt("", i,0);
          modelo.setValueAt("", i,1);
          modelo.setValueAt("", i,2);
          modelo.setValueAt("", i,3);
          modelo.setValueAt("", i,4);
          modelo.setValueAt("", i,5);
          modelo.setValueAt("", i,6);
          totalpedido.setText("");
          
      }
      
      
       
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable listadecliente;
    private javax.swing.JTable listadeproduto;
    private javax.swing.JTable listapedido;
    private javax.swing.JTextField totalpedido;
    // End of variables declaration//GEN-END:variables

}
