/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import Modelo.bean.Produto;
import Modelo.dao.Produtodao;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Matheus
 */
public class TelaAtualizacaodeProduto extends javax.swing.JFrame {

    /**
     * Creates new form TelaAtualizacaodeProduto
     */
    public TelaAtualizacaodeProduto() {
        initComponents();

        atualizacaoProduto();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        jTextField4 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableAtualizacaodeProduto = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldCodProduto = new javax.swing.JTextField();
        jTextFieldNomeProduto = new javax.swing.JTextField();
        jTextFieldValorProduto = new javax.swing.JTextField();
        textobuscarproduto = new javax.swing.JTextField();
        aTTBuscarProduto = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        jButton3.setText("jButton3");

        jTextField4.setText("jTextField4");

        jLabel4.setText("jLabel4");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Atualização de Produto");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setForeground(new java.awt.Color(0, 0, 0));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        jTableAtualizacaodeProduto.setBackground(new java.awt.Color(255, 255, 255));
        jTableAtualizacaodeProduto.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTableAtualizacaodeProduto.setForeground(new java.awt.Color(0, 0, 0));
        jTableAtualizacaodeProduto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CodProduto", "NomeProduto", "ValorProduto"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableAtualizacaodeProduto.setGridColor(new java.awt.Color(255, 255, 255));
        jTableAtualizacaodeProduto.setSelectionBackground(new java.awt.Color(204, 204, 204));
        jTableAtualizacaodeProduto.setSelectionForeground(new java.awt.Color(0, 0, 0));
        jTableAtualizacaodeProduto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableAtualizacaodeProdutoMouseClicked(evt);
            }
        });
        jTableAtualizacaodeProduto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTableAtualizacaodeProdutoKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTableAtualizacaodeProduto);

        jLabel1.setText("Codigo Produto");

        jLabel2.setText("Nome Produto");

        jLabel3.setText("Valor Produto");

        textobuscarproduto.setText("Buscar  Produto");

        aTTBuscarProduto.setText("Buscar");
        aTTBuscarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aTTBuscarProdutoActionPerformed(evt);
            }
        });

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/WhatsApp Image 2021-08-25 at 12.38.07.jpeg"))); // NOI18N
        jLabel5.setText("jLabel5");

        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton1.setText("Atualizar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jTextFieldCodProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(63, 63, 63)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jTextFieldNomeProduto))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jTextFieldValorProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(57, 57, 57))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 233, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(34, 34, 34)
                        .addComponent(jButton2)
                        .addGap(231, 231, 231)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(textobuscarproduto, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(aTTBuscarProduto)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane1)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCodProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldNomeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldValorProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textobuscarproduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(aTTBuscarProduto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addGap(8, 8, 8))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void aTTBuscarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aTTBuscarProdutoActionPerformed
        // Botão buscar produto;
        buscarproduto(textobuscarproduto.getText());

    }//GEN-LAST:event_aTTBuscarProdutoActionPerformed

    private void jTableAtualizacaodeProdutoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTableAtualizacaodeProdutoKeyReleased
        // Seta informações nos campos

        if (jTableAtualizacaodeProduto.getSelectedRow() != -1) {

            jTextFieldCodProduto.setText(jTableAtualizacaodeProduto.getValueAt(jTableAtualizacaodeProduto.getSelectedRow(), 0).toString());
            jTextFieldNomeProduto.setText(jTableAtualizacaodeProduto.getValueAt(jTableAtualizacaodeProduto.getSelectedRow(), 1).toString());
            jTextFieldValorProduto.setText(jTableAtualizacaodeProduto.getValueAt(jTableAtualizacaodeProduto.getSelectedRow(), 2).toString());

        }

    }//GEN-LAST:event_jTableAtualizacaodeProdutoKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // Atualiza o Produto no bando de dados.
        if (jTableAtualizacaodeProduto.getSelectedRow() != -1) {

            Produto p = new Produto(); // 
            Produtodao pdao = new Produtodao();

            p.setCodproduto((int) jTableAtualizacaodeProduto.getValueAt(jTableAtualizacaodeProduto.getSelectedRow(), 0));//busca a linha selecionada na lista
            p.setNomeproduto(jTextFieldNomeProduto.getText()); //pega o valor docampo nome da tela e seta em produto
            p.setPrecoproduto(Double.parseDouble(jTextFieldValorProduto.getText()));

            System.out.println(jTableAtualizacaodeProduto.getSelectedRow());
            System.out.println(p.getCodproduto());
            System.out.println(p.getNomeproduto());
            System.out.println(p.getPrecoproduto());

            jTextFieldCodProduto.setText("");
            jTextFieldNomeProduto.setText("");
            jTextFieldValorProduto.setText("");

            pdao.AtualizarProduto(p);

            atualizacaoProduto();

        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTableAtualizacaodeProdutoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableAtualizacaodeProdutoMouseClicked
        // TODO add your handling code here:

        if (jTableAtualizacaodeProduto.getSelectedRow() != -1) {

            jTextFieldCodProduto.setText(jTableAtualizacaodeProduto.getValueAt(jTableAtualizacaodeProduto.getSelectedRow(), 0).toString());
            jTextFieldNomeProduto.setText(jTableAtualizacaodeProduto.getValueAt(jTableAtualizacaodeProduto.getSelectedRow(), 1).toString());
            jTextFieldValorProduto.setText(jTableAtualizacaodeProduto.getValueAt(jTableAtualizacaodeProduto.getSelectedRow(), 2).toString());
        }


    }//GEN-LAST:event_jTableAtualizacaodeProdutoMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // Botão Cancelar

        TelaInformacoesProduto tela = new TelaInformacoesProduto();

        tela.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaAtualizacaodeProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaAtualizacaodeProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaAtualizacaodeProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAtualizacaodeProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaAtualizacaodeProduto().setVisible(true);
            }
        });
    }

    public void atualizacaoProduto() {

        DefaultTableModel modelo = (DefaultTableModel) jTableAtualizacaodeProduto.getModel();
        modelo.setNumRows(0);
        Produtodao pdao = new Produtodao();

        for (Produto p : pdao.Listarproduto()) {

            modelo.addRow(new Object[]{
                p.getCodproduto(),
                p.getNomeproduto(),
                p.getPrecoproduto(),});

        }
    }

    public void buscarproduto(String busca) {
         //busca de produtos .
        DefaultTableModel modelo = (DefaultTableModel) jTableAtualizacaodeProduto.getModel();
        modelo.setNumRows(0);
        Produtodao pdao = new Produtodao();

        for (Produto p : pdao.buscaProduto(busca)) {

            modelo.addRow(new Object[]{
                p.getCodproduto(),
                p.getNomeproduto(),
                p.getPrecoproduto(),});
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aTTBuscarProduto;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableAtualizacaodeProduto;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextFieldCodProduto;
    private javax.swing.JTextField jTextFieldNomeProduto;
    private javax.swing.JTextField jTextFieldValorProduto;
    private javax.swing.JTextField textobuscarproduto;
    // End of variables declaration//GEN-END:variables
}
