/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import Modelo.bean.CadastroFornecedor;
import Modelo.dao.CadastroFornecedordao;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Matheus
 */
public class TelaAlterarCadFornecedor extends javax.swing.JFrame {

    /**
     * Creates new form TelaAlterarCadFornecedor
     */
    public TelaAlterarCadFornecedor() {
        initComponents();
        tamanholista();
        listarfornecedor();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        txtNome = new javax.swing.JTextField();
        txtEndereco = new javax.swing.JTextField();
        txtcep = new javax.swing.JTextField();
        txtcnpj = new javax.swing.JFormattedTextField();
        txtcontato = new javax.swing.JTextField();
        txtcontato2 = new javax.swing.JTextField();
        txtData = new javax.swing.JTextField();
        selecao = new javax.swing.JComboBox<>();
        textobusca = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listafornecedor = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel2.setText("Nome: ");

        jLabel3.setText("Id:");

        jLabel4.setText("Endereço: ");

        jLabel5.setText("Cep: ");

        jLabel6.setText("Cnpj:");

        jLabel7.setText("Contato1: ");

        jLabel8.setText("Data:");

        jLabel9.setText("Contato2: ");

        try {
            txtcnpj.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###/####-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        selecao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nome", "Id" }));
        selecao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selecaoActionPerformed(evt);
            }
        });

        jButton1.setText("Buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        listafornecedor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        listafornecedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listafornecedorMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(listafornecedor);

        jButton2.setText("Cadastrar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("  Editar   ");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Remover");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtcnpj))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtcep, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel7)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtcontato, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jLabel9)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtcontato2)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(selecao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textobusca, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)
                        .addGap(101, 101, 101)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selecao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(textobusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtcep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtcnpj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtcontato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(txtcontato2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3)
                        .addGap(18, 18, 18)
                        .addComponent(jButton4)))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void selecaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selecaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selecaoActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        TelaCadastroFornecedor tela = new TelaCadastroFornecedor();
        tela.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:.
        
       int teste = selecao.getSelectedIndex();
          if(teste == 0){
              
              
              buscarfornecedor(textobusca.getText());

            } else{
                
                buscarfornecedoroid(textobusca.getText());
                
            } 
        
 
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void listafornecedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listafornecedorMouseClicked
 
        if(selecao.getSelectedIndex() == 0 ){   
         
            String busca = listafornecedor.getValueAt(listafornecedor.getSelectedRow(), 1).toString();
            //textobusca.setText(listafornecedor.getValueAt(listafornecedor.getSelectedRow(), 1).toString());
            
            CadastroFornecedordao caddao = new CadastroFornecedordao();
 
        
        for (CadastroFornecedor cad : caddao.buscarfonecedorpuro(busca) ){
            
            Object [] dados = {
              cad.getNomefornecedor(),
              cad.getEndereco(),
              cad.getCep(),
              cad.getCpnj(),
              cad.getContato1(),
              cad.getContato2(),
              cad.getCidade(),
              cad.getBairro(),
              cad.getData(),
              cad.getId()      
                
            };
            
            txtData.setText(String.valueOf(cad.getData()));
            txtId.setText(String.valueOf(cad.getId()));
            txtNome.setText(cad.getNomefornecedor());
            txtEndereco.setText(cad.getEndereco());
            txtEndereco.setText(cad.getEndereco());
            txtcep.setText(String.valueOf(cad.getCep()));
            txtcnpj.setText(cad.getCpnj());
            txtcontato.setText(String.valueOf(cad.getContato1()));
            txtcontato2.setText(String.valueOf(cad.getContato2()));      
        }
        } else {
                 String busca = listafornecedor.getValueAt(listafornecedor.getSelectedRow(), 0).toString();
            textobusca.setText(listafornecedor.getValueAt(listafornecedor.getSelectedRow(), 0).toString());
            
            
            System.out.println("Valor " + selecao.getSelectedIndex());
            System.out.println(busca);
            
            CadastroFornecedordao caddao = new CadastroFornecedordao();
 
        
        for (CadastroFornecedor cad : caddao.buscarfonecedorpuro(busca) ){
            
            Object [] dados = {
              cad.getNomefornecedor(),
              cad.getEndereco(),
              cad.getCep(),
              cad.getCpnj(),
              cad.getContato1(),
              cad.getContato2(),
              cad.getCidade(),
              cad.getBairro(),
              cad.getData(),
              cad.getId()      
                
            };
            
            txtData.setText(String.valueOf(cad.getData()));
            txtId.setText(String.valueOf(cad.getId()));
            txtNome.setText(cad.getNomefornecedor());
            txtEndereco.setText(cad.getEndereco());
            txtEndereco.setText(cad.getEndereco());
            txtcep.setText(String.valueOf(cad.getCep()));
            txtcnpj.setText(cad.getCpnj());
            txtcontato.setText(String.valueOf(cad.getContato1()));
            txtcontato2.setText(String.valueOf(cad.getContato2())); 
        } 
         
        } 
            
        
    }//GEN-LAST:event_listafornecedorMouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        
        
        if (listafornecedor.getSelectedRow() != -1){
            
            CadastroFornecedordao caddao = new CadastroFornecedordao();
            
            CadastroFornecedor cad = new CadastroFornecedor();
            
            cad.setNomefornecedor(txtNome.getText());
            cad.setEndereco(txtEndereco.getText());
            cad.setCep(Integer.parseInt(txtcep.getText()));
            cad.setCpnj(txtcnpj.getText());
            cad.setContato1(Integer.parseInt(txtcontato.getText()));
            cad.setContato2(Integer.parseInt(txtcontato2.getText()));
            cad.setData(txtData.getText());
            cad.setId(Integer.parseInt(txtId.getText()));
            
            caddao.alteracaofornecedor(cad);
            
            listarfornecedor();
            
            
        } else {
            
            JOptionPane.showMessageDialog(null, "Selecione um fornecedor para alterar");
            
        }
        
        
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // 
        
        if (listafornecedor.getSelectedRow() != -1){
            
            CadastroFornecedordao caddao = new CadastroFornecedordao();
            
            CadastroFornecedor cad = new CadastroFornecedor();
            
            cad.setId(Integer.parseInt(txtId.getText()));
            
            caddao.deletarfornecedor(cad);
            
            listarfornecedor();
        } else {
            
            JOptionPane.showMessageDialog(null,"Selecione um fornecedor para excluir");
        }
        
        
    }//GEN-LAST:event_jButton4ActionPerformed
   
     
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaAlterarCadFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaAlterarCadFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaAlterarCadFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAlterarCadFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaAlterarCadFornecedor().setVisible(true);
            }
        });
    }
    
    public void tamanholista (){
        
        listafornecedor.setAutoResizeMode(listafornecedor.AUTO_RESIZE_OFF);
        listafornecedor.getColumnModel().getColumn(0).setPreferredWidth(100);
        listafornecedor.getColumnModel().getColumn(1).setPreferredWidth(350);
        
        
    }
    
    
    public void buscarfornecedor (String buscar){
        
        DefaultTableModel modelo = (DefaultTableModel) listafornecedor.getModel();
        modelo.setRowCount(0);
        CadastroFornecedordao cad = new CadastroFornecedordao();
        
        for(CadastroFornecedor cadastro : cad.buscarfonecedor(buscar)){
            
            modelo.addRow(new Object[]{
                
                cadastro.getId(),
                cadastro.getNomefornecedor()
                       
            });
            
        }       
    }
    
     public void listarfornecedor(){
     
         DefaultTableModel modelo = (DefaultTableModel) listafornecedor.getModel();
         modelo.setRowCount(0);
        CadastroFornecedordao cadastro = new CadastroFornecedordao();
         
         for(CadastroFornecedor cad : cadastro.listarfonecedor()){
             modelo.addRow(new Object[]{
                 
//              
                 cad.getId(),
                 cad.getNomefornecedor(),
              
                 
                 
             });
             
         } 
    }
     
     public void buscarfornecedoroid (String buscar){
        
        DefaultTableModel modelo = (DefaultTableModel) listafornecedor.getModel();
        modelo.setRowCount(0);
        CadastroFornecedordao cad = new CadastroFornecedordao();
        
        for(CadastroFornecedor cadastro : cad.buscarfonecedorid(buscar)){
            
            modelo.addRow(new Object[]{
                
                cadastro.getId(),
                cadastro.getNomefornecedor()
                       
            });
        }  
        } 
     
     

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable listafornecedor;
    private javax.swing.JComboBox<String> selecao;
    private javax.swing.JTextField textobusca;
    private javax.swing.JTextField txtData;
    private javax.swing.JTextField txtEndereco;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtcep;
    private javax.swing.JFormattedTextField txtcnpj;
    private javax.swing.JTextField txtcontato;
    private javax.swing.JTextField txtcontato2;
    // End of variables declaration//GEN-END:variables
}
